ALTER TABLE minerstats ADD COLUMN hashratetype VARCHAR;

CREATE INDEX IDX_MINERSTATS_POOL_CREATED_HASHRATETYPE on minerstats(poolid, created, hashratetype);
CREATE INDEX IDX_MINERSTATS_POOL_MINER_CREATED_HASHRATETYPE on minerstats(poolid, miner, created, hashratetype);
CREATE INDEX IDX_MINERSTATS_POOL_MINER_WORKER_CREATED_HASHRATE_HASHRATETYPE on minerstats(poolid, miner, worker, created desc, hashrate, hashratetype);

DROP INDEX IDX_MINERSTATS_POOL_CREATED;
DROP INDEX IDX_MINERSTATS_POOL_MINER_CREATED;
DROP INDEX IDX_MINERSTATS_POOL_MINER_WORKER_CREATED_HASHRATE;

