name: docker

on:
  pull_request:
  push:
    tags:        
      - v*.*.*

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            aczd1yuv.gra7.container-registry.ovh.net/stratumfarm/miningcore
          tags: |
            type=raw,event=tag,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=semver,event=tag,pattern={{version}}
            type=semver,event=tag,pattern={{major}}.{{minor}}
            type=ref,event=pr
      -
        name: dockerhub login
        uses: docker/login-action@v1
        with:
          registry: aczd1yuv.gra7.container-registry.ovh.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: build and push the image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - 
        name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
